import { useEffect, useState } from "react";
import { api } from "../../api";
import type { CaseView, Communication } from "../../types";
import { Badge, Card } from "../shared/common";

const STATUS_TONE: Record<string, string> = { RESOLVED: "success", HUMAN_TAKEOVER: "danger", VERIFYING: "info" };

/** Case Agent timeline and Communication Agent message for one incident (both built from persisted records). */
export function CaseCard({ incidentId, refreshKey }: { incidentId: string; refreshKey: string }) {
  const [caseView, setCase] = useState<CaseView | null>(null);
  const [message, setMessage] = useState<Communication | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let live = true;
    Promise.all([api.caseOf(incidentId), api.communication(incidentId)])
      .then(([c, m]) => { if (live) { setCase(c); setMessage(m); setError(null); } })
      .catch((e) => { if (live) setError(e instanceof Error ? e.message : String(e)); });
    return () => { live = false; };
  }, [incidentId, refreshKey]);

  return (
    <Card question="What is the full story, and what do we tell people?" title="Case & communication">
      {error && <div className="alert alert-danger" role="alert">{error}</div>}
      {caseView && (
        <>
          <div className="row"><span className="muted">Case status</span><Badge tone={STATUS_TONE[caseView.final_status] ?? "neutral"}>{caseView.final_status}</Badge></div>
          <details open>
            <summary>Timeline ({caseView.timeline.length})</summary>
            <ul className="plain">
              {caseView.timeline.map((e, n) => (
                <li key={n} className="small">
                  <strong>{e.stage}</strong> <span className="muted">· {new Date(e.at).toLocaleString()} · Source: {e.source}</span>
                  <div>{e.summary}</div>
                </li>
              ))}
            </ul>
          </details>
        </>
      )}
      {message && (
        <details>
          <summary>Status message: {message.subject}</summary>
          <pre className="small" style={{ whiteSpace: "pre-wrap" }}>{message.body}</pre>
          <p className="muted small">Generated by: {message.generated_by}</p>
        </details>
      )}
    </Card>
  );
}
